- name: checking data types
  hosts: localhost
  vars:
    NAME: Chaitanya #key value
    SKILLS: # Skills is list type
    - Devops
    - AWS
    - Docker
    - GIT
    - Linux
    - Ansible
    Experience:  # Experience is map type. It contains key value pair
      Devops: 6
      AWS: 5
      Docker: 4
    Trainer: true # boolean type
  tasks:
  - name: print key value pair
    ansible.bulitin.debug:
      msg: "name: {{NAME}}"

  - name: print list
    ansible.bulitin.debug:
      msg: "skills: {{SKILLS}}"
    
  - name: print map
    ansible.bulitin.debug:
      msg: "Experience: {{Experience}}"

  - name: print boolean
    ansible.bulitin.debug:
      msg: "Is he Trainer: {{Trainer}}"


