- name: loops
  hosts: localhost
  become: yes
  tasks:
  - name: print persons
    ansible.builtin.package:
      name: "Hello {{item}}" # item is a default keyword
      state: present
    loop:
    - git
    - mysql
    - postfix
    